language: node_js
os: linux

node_js:
  - "14"

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

before_install:
  - npm install -g yarn

install:
  - rm -rf dist node_modules
  - yarn

script:
  - yarn lint
  - yarn test
  - yarn e2e
  - yarn build --base-href https://szgabsz91.github.io/iit-www/

deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  edge: true
  cleanup: false
  local_dir: dist/iit-www
