language: node_js
os: linux

node_js:
  - "12"

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

before_install:
  - npm install -g yarn

install:
  - rm -rf dist node_modules
  - yarn
  - rm -rf node_modules/protractor/node_modules/webdriver-manager
  - mv node_modules/webdriver-manager node_modules/protractor/node_modules

script:
  - yarn lint
  - yarn test
  - yarn e2e
  - yarn build:prod --base-href https://szgabsz91.github.io/iit-www/en/
  - yarn build:hu:prod --base-href https://szgabsz91.github.io/iit-www/ --deleteOutputPath=false

deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  edge: true
  cleanup: false
  local_dir: dist/iit-www
