language: node_js
os: linux

node_js:
  - "14"

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

before_install:
  - npm install -g yarn

install:
  - rm -rf dist node_modules
  - yarn

script:
  - yarn lint
  - yarn test
  - yarn e2e
  - yarn build --base-href https://iit-szg.web.app/

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
