name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn
      - name: Lint project
        run: yarn lint
      - name: Execute unit tests
        run: yarn test
      - name: Execute E2E tests
        run: yarn e2e
      - name: Build project
        run: yarn build
