name: Build

on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Graphviz
        run: sudo apt-get install graphviz
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: volta-cli/action@v4
        with:
          node-version: 20.11.1
          yarn-version: 1.22.21
      - name: Install dependencies
        run: yarn
      - name: Lint project
        run: yarn lint
      - name: Execute unit tests
        run: yarn test
      - name: Execute E2E tests
        run: yarn e2e
      - name: Build project
        run: yarn build --base-href https://iit-szg--rc-vowdo21i.web.app/
      - name: Merge locale dependent service workers
        run: ./scripts/merge-service-workers.js
      - name: Recalculate ngsw hash table
        run: ./scripts/recalculate-ngsw-hash-table.js
      - name: Deploy project to Firebase RC channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_IIT_SZG }}'
          projectId: iit-szg
          channelId: rc
          expires: 1d
      - name: Execute Lighthouse analysis
        run: yarn lighthouse
        env:
          LHCI_URL: https://iit-szg--rc-vowdo21i.web.app/en/
