name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn
      - name: Build project
        run: yarn build --base-href https://iit-szg.web.app/
      - name: Deploy project to Firebase
        run: yarn deploy --token ${{ secrets.FIREBASE_TOKEN }}
