name: Release and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Release and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install Graphviz
        run: sudo apt-get install graphviz
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: volta-cli/action@v4
        with:
          node-version: 20.14.0
          yarn-version: 1.22.22
      - name: Install dependencies
        run: yarn
      - name: Lint project
        run: yarn lint
      - name: Execute unit tests
        run: yarn test
      - name: Execute E2E tests
        run: yarn e2e
      - name: Bump version
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn release
      - name: Build project
        run: yarn build --base-href https://iit-szg--rc-ml5sg9xk.web.app/
      - name: Merge locale dependent service workers
        run: ./scripts/merge-service-workers.js
      - name: Recalculate ngsw hash table for RC deployment
        run: ./scripts/recalculate-ngsw-hash-table.js
      - name: Deploy project to Firebase RC channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_IIT_SZG }}'
          projectId: iit-szg
          channelId: rc
          expires: 1d
      - name: Execute Lighthouse analysis
        run: yarn lighthouse
        env:
          LHCI_URL: https://iit-szg--rc-ml5sg9xk.web.app/en/
      - name: Finalize the base URL for live deployment
        run: |
          sed -i 's,https://iit-szg--rc-ml5sg9xk.web.app/,https://iit-szg.web.app/,g' dist/iit-szg/*/index.html
          sed -i 's,https://iit-szg--rc-ml5sg9xk.web.app/,https://iit-szg.web.app/,g' dist/iit-szg/ngsw.json
      - name: Recalculate ngsw hash table for live deployment
        run: ./scripts/recalculate-ngsw-hash-table.js
      - name: Deploy project to Firebase live channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_IIT_SZG }}'
          projectId: iit-szg
          channelId: live
