name: Release and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Release and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install Graphviz
        run: sudo apt-get install graphviz
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Lint project
        run: yarn lint
      - name: Execute unit tests
        run: yarn test
      - name: Execute E2E tests
        run: yarn e2e
      - name: Bump version
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn release
      - name: Build project
        run: yarn build --base-href https://iit-szg.web.app/
      - name: Deploy project to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GH_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_IIT_SZG }}'
          projectId: iit-szg
          channelId: live
